version: '3.8'
services:
  backend:
    build:
      dockerfile: Dockerfile_backend
    container_name: star_burger_backend
    restart: always
    volumes:
      - media_value:/opt/app/media/
      - static_value:/opt/app/staticfiles/
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"


  frontend:
    build:
      dockerfile: Dockerfile_frontend
    container_name: star_burger_frontend
    restart: always
    command: ./node_modules/.bin/parcel watch ./bundles-src/index.js --dist-dir bundles --public-url "./"

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  static_value:
  media_value:
  frontend_value:
  db_value:
