FROM python:3.9.16-slim-buster

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR opt/app

COPY requirements.txt .
RUN apt-get update && apt-get install -y libpq-dev build-essential
RUN  pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python3", "manage.py", "collectstatic"]
