version: '3.8'
services:
  backend:
    build:
      dockerfile: Dockerfile_backend
    container_name: star_burger_backend
    restart: always
    volumes:
      - media_value:/opt/app/media/
      - static_value:/opt/app/staticfiles/
    env_file:
      - .env
    depends_on:
      - db
    command: gunicorn -w 3 -b 0.0.0.0:8000 star_burger.wsgi

  frontend:
    build:
      dockerfile: Dockerfile_frontend
    container_name: star_burger_frontend
    command: ./node_modules/.bin/parcel watch ./bundles-src/index.js --dist-dir bundles --public-url "./"

  db:
      image: postgres:13.0-alpine
      volumes:
        - db_value:/var/lib/postgresql/data
      env_file:
        - .env
#      ports:
#        - "5432:5432"

  nginx:
    image: nginx:1.25.0-alpine-slim
    ports:
      - 80:80
    volumes:
      - ./proxy_params:/etc/nginx/proxy_params
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/staticfiles/
      - media_value:/var/html/media/

volumes:
  static_value:
  media_value:
  frontend_value:
  db_value:
