# Generated by Django 3.2.15 on 2023-03-08 14:54

from django.db import migrations


def set_price_to_products_of_order(apps, schema_editor):
    OrderProducts = apps.get_model('foodcartapp', 'OrderProducts')
    Product = apps.get_model('foodcartapp', 'Product')

    products = Product.objects.all()
    for product in products:
        OrderProducts.objects.filter(product=product).update(price=product.price)


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_orderproducts_price'),
    ]

    operations = [
        migrations.RunPython(set_price_to_products_of_order),
    ]
