# Generated by Django 3.2.15 on 2023-03-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20230308_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('ACCEPTED', 'Подтвержден'), ('PREPARING', 'Готовится'), ('READY', 'Готов'), ('DELIVERING', 'Доставляется'), ('FINISHED', 'Закончен')], default='CREATED', max_length=50, verbose_name='Статус'),
        ),
    ]
