# Generated by Django 3.2.15 on 2023-03-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20230309_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Наличными курьеру'), ('CARD', 'Картой онлайн'), ('NOT_CHOOSEN', 'Не выбран')], default='NOT_CHOOSEN', max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
