# Generated by Django 3.2.15 on 2023-03-11 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='responsible_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant', to='foodcartapp.restaurant', verbose_name='назначенный ресторан'),
        ),
    ]
