# Generated by Django 3.2.15 on 2023-03-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20230314_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-status',), 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
    ]
