# Generated by Django 3.2.15 on 2023-03-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('PREPARING', 'Готовится'), ('READY', 'Готов'), ('DELIVERING', 'Доставляется'), ('FINISHED', 'Закончен')], default='CREATED', max_length=50, verbose_name='Статус'),
        ),
    ]
